function publicAIError(error, fallbackMessage) {
  const status = Number(error?.status);
  const message = String(error?.message || '');

  // Preserve messages generated by our own input validation, but never expose
  // provider SDK errors, request payloads, or upstream response details.
  if ((status === 400 || status === 413) && message) {
    return { status, message };
  }
  if (status === 503 && /not configured|not available|unavailable/i.test(message)) {
    return { status, message };
  }
  return { status: status >= 400 && status < 500 ? 502 : 502, message: fallbackMessage };
}

module.exports = { publicAIError };
