import { Link } from 'react-router-dom';
import { ArrowRightIcon, PlayIcon } from '@heroicons/react/24/outline';

export default function ResumeLearningCard({ href, title, detail, progress, className = '', variant = 'default' }) {
  if (!href) return null;
  if (variant === 'minimal') {
    return <Link to={href} className={`group flex items-center justify-between gap-5 border-b border-line-soft py-4 transition-colors hover:border-accent/50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent ${className}`}><div className="min-w-0"><p className="text-sm font-medium text-text-muted">Continue</p><h2 className="mt-1 truncate font-display text-xl font-bold text-text-primary transition-colors group-hover:text-accent">{title}</h2>{detail && <p className="mt-1 truncate text-sm font-medium text-text-muted">{detail}</p>}{Number.isFinite(progress) && <div className="mt-3 h-1.5 w-48 overflow-hidden rounded-full bg-surface-soft" role="progressbar" aria-label={`${title} progress`} aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(progress)}><div className="h-full rounded-full bg-accent" style={{ width: `${Math.max(0, Math.min(100, progress))}%` }} /></div>}</div><span className="inline-flex shrink-0 items-center gap-2 text-sm font-bold text-accent">Open <ArrowRightIcon className="h-4 w-4 transition-transform group-hover:translate-x-1" aria-hidden="true" /></span></Link>;
  }
  return <Link to={href} className={`group flex flex-col gap-5 rounded-3xl bg-surface-raised p-6 shadow-card card-lift sm:flex-row sm:items-center sm:justify-between ${className}`}><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-accent-soft text-accent"><PlayIcon className="h-6 w-6" aria-hidden="true" /></span><div><p className="text-[11px] font-bold uppercase tracking-[0.13em] text-text-dim">Ready to resume</p><h2 className="mt-1 font-display text-xl font-extrabold text-text-primary">{title}</h2>{detail && <p className="mt-1 text-sm font-medium text-text-muted">{detail}</p>}{Number.isFinite(progress) && <div className="mt-3 h-1.5 w-48 overflow-hidden rounded-full bg-surface-soft" role="progressbar" aria-label={`${title} progress`} aria-valuemin="0" aria-valuemax="100" aria-valuenow={Math.round(progress)}><div className="h-full rounded-full bg-accent" style={{ width: `${Math.max(0, Math.min(100, progress))}%` }} /></div>}</div></div><span className="inline-flex items-center gap-2 text-sm font-bold text-accent">Continue <ArrowRightIcon className="h-4 w-4 transition-transform group-hover:translate-x-1" aria-hidden="true" /></span></Link>;
}
